version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: cloudsigma.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html/
    networks:
      - app-network

  db:
    image: mysql:5.7.32
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: F1s0ft@123
      MYSQL_PASSWORD: Esewa@123#
      MYSQL_USER: esewa
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
